Passage en flexbox de category.html.twig + preparation de quelques re…
WildCodeSchool/tlse-php-202109-p2-rgb pull request #25
Opened 2021-11-08 21:23 UTC by benjamin31200

…quete de base de donnee pour Liste mes jeux

2021-11-08 21:24 UTC, benjamin31200 commented on src/Controller/CategoryController.php
> +        // foreach ($categoriesId as $categorieId) {
algo non terminé passé en commentaire en attendant

2021-11-08 21:27 UTC, benjamin31200 reviewed
informations sur le push

2021-11-08 21:27 UTC, benjamin31200 commented on src/Model/CategoryManager.php
> +
requete en base de donnée pour l'algo que j'ai passé en commentaire

2021-11-08 21:27 UTC, benjamin31200 commented on src/View/Category/index.html.twig
> +				{# {% for nameGameById in namesGameById %}
boucle twig pour afficher l'algo, pareil en commentaire en attendant

2021-11-09 09:55 UTC, Wambrat requested changes

2021-11-09 09:55 UTC, Wambrat commented on src/Model/ListMyGamesManager.php
> +            "SELECT user_id
fait une requete preparer stp ^^

2021-11-09 22:11 UTC, closed without merging