Feature/search
WildCodeSchool/tlse-php-202109-p2-rgb pull request #37
Opened 2021-11-15 13:24 UTC by PerrinGaetan

Add search bar to research games of user list by name.

2021-11-15 22:55 UTC, Wambrat requested changes

2021-11-15 22:55 UTC, Wambrat commented on public/assets/css/style.css
> +.userPseudo{
.userPseudo {
    manque cet espace

2021-11-15 22:56 UTC, Wambrat commented on public/assets/css/style.css
> +.userPseudo{
apres pseudo dsl ^^

2021-11-16 11:26 UTC, bastienwcs approved these changes

2021-11-16 11:27 UTC, PerrinGaetan commented
J'ai fais le plus attention possible aux espaces avant apres chaque parenthèses, accollades, virgules, voyelles et consonnes ;-)
J'espère ne rien avoir oublié.

2021-11-16 12:27 UTC, Wambrat approved these changes

2021-11-16 12:28 UTC, merged