création des commentaires en base de donnée
WildCodeSchool/tlse-php-202109-p2-rgb pull request #38
Opened 2021-11-15 22:39 UTC by benjamin31200

insertion des commentaires en base de donnée possible, il y'a juste quelques petits détails à régler.

2021-11-15 23:07 UTC, Wambrat requested changes

2021-11-15 23:07 UTC, Wambrat commented on src/Model/DescriptionGameModel.php
> +
un saut de ligne en trop

2021-11-15 23:10 UTC, Wambrat commented
merde dsl c plus moi le reviewer faite comme si de rien n'était

2021-11-16 08:20 UTC, PerrinGaetan requested changes

2021-11-16 09:47 UTC, benjamin31200 commented on src/Model/DescriptionGameModel.php
> +        VALUES (:commentaire, :date, " . $getGameId . ", " . $getUserId . ")"
j'ai modifier et je l'ai passé en bindvalue

2021-11-16 09:48 UTC, benjamin31200 commented on src/Model/DescriptionGameModel.php
>              return $likes;
c'est le code à Ryan à voir avec lui

2021-11-16 09:48 UTC, benjamin31200 reviewed
All good

2021-11-16 12:24 UTC, PerrinGaetan approved these changes
Après vérification tout semble bon.

Aurais je raté quelque chose Bastien ?

2021-11-16 12:32 UTC, bastienwcs approved these changes

2021-11-16 13:06 UTC, Wambrat approved these changes

2021-11-16 13:06 UTC, merged