Feature/assess
WildCodeSchool/tlse-php-202109-p2-rgb pull request #39
Opened 2021-11-16 13:06 UTC by Wambrat

2021-11-16 16:27 UTC, PerrinGaetan requested changes

2021-11-16 16:27 UTC, PerrinGaetan commented on src/Controller/DescriptionGameController.php
> +                    return $error = "Votre commentaire ne doit pas être vide";
return $error = "..." ? ça marche ça ?

2021-11-16 17:41 UTC, PerrinGaetan requested changes

2021-11-16 17:41 UTC, PerrinGaetan commented on src/View/Home/descriptionGame.html.twig
> +      </div>
probleme d'indentation : la div fermante pas aligné sur l'ouvrante et le endif pareil.

2021-11-17 09:22 UTC, PerrinGaetan approved these changes
Pour moi c'est ok.
Bastien tu valide ?

2021-11-17 09:31 UTC, bastienwcs requested changes

2021-11-17 09:31 UTC, bastienwcs commented on src/Model/DescriptionGameModel.php
> +            80 => 'Tacos',
à la limite "Golden Tacos" pour le plus élevé, mais honnêtement, je pense qu'il y a mieux que ça

2021-11-17 09:31 UTC, bastienwcs commented on src/View/Home/descriptionGame.html.twig
> +    <h2 style='text-align:center; margin:20px auto 20px'>{{ game['name'] }}</h2>
pas de style inline, faire du CSS !

donc modifier TOUS les endroits où y'a du style=

2021-11-17 09:31 UTC, bastienwcs commented on src/View/Home/descriptionGame.html.twig
> +		<div class="commentaire">
mal indenté

2021-11-17 11:02 UTC, PerrinGaetan approved these changes
Après vérification, toutes les corrections ont été faite (si je n'en ai pas raté une)

2021-11-17 11:10 UTC, bastienwcs approved these changes

2021-11-17 11:28 UTC, merged