Feature/espace commentaire
WildCodeSchool/tlse-php-202109-p2-rgb pull request #41
Opened 2021-11-16 21:07 UTC by benjamin31200

Version de l'espace commentaire fonctionnel coté back comme front.

2021-11-16 22:16 UTC, PerrinGaetan requested changes
Parfait, juste un endroit avec saut de ligne en trop et le nommage d'une methode à changer et ça sera bon pour moi.

2021-11-16 22:16 UTC, PerrinGaetan commented on public/assets/css/descriptionGame.css
> +
saut de ligne en trop

2021-11-16 22:16 UTC, PerrinGaetan commented on src/Controller/DescriptionGameController.php
> +        $getAllCommentsByGame = $gameModel->selectAllCommentByGame();
selectAllCommentsByGame plutot que selectAllCommentByGame

2021-11-16 22:16 UTC, PerrinGaetan commented on src/Model/DescriptionGameModel.php
> +    public function selectAllCommentByGame()
Comment au pluriel => selectAllCommentsByGame

2021-11-17 09:15 UTC, PerrinGaetan approved these changes
c'est bon pour moi.
Bastien j'ai oublié quelque chose ?

2021-11-17 09:27 UTC, bastienwcs requested changes

2021-11-17 09:27 UTC, bastienwcs commented on src/View/Home/index.html.twig
> +				<img src="/assets/images/pictures_game/covers/hades.jpg" alt=""></div>
les div doivent revenir à la ligne

2021-11-17 09:27 UTC, bastienwcs commented on src/View/Home/index.html.twig
> +</div>{% endblock %}
le {% endblock %} doit être sur une nouvelle ligne

2021-11-17 09:27 UTC, bastienwcs commented on src/View/ListMyGames/index.html.twig
> +			!</p>
le < /p > sur une nouvelle ligne

2021-11-17 09:27 UTC, bastienwcs commented on src/View/ListMyGames/index.html.twig
> +					<span class="toggle__text">En progression</span>
Je dirais plus "En cours" que "En progression"

2021-11-17 09:47 UTC, bastienwcs requested changes

2021-11-17 09:47 UTC, bastienwcs commented on src/View/ListMyGames/index.html.twig
> +					<span class="toggle__text">En Cours</span>
En cours (pas de majuscule à Cours)

2021-11-17 09:47 UTC, bastienwcs commented on src/View/ListMyGames/index.html.twig
> +					<a class="dropdown-item" href="#">En progression</a>
En cours (je ne l'avais pas vu avant)

2021-11-17 10:33 UTC, benjamin31200 reviewed
Logiquement tout est bon

2021-11-17 10:54 UTC, PerrinGaetan requested changes

2021-11-17 10:54 UTC, PerrinGaetan commented on src/View/Home/index.html.twig
> +</div>
ligne 32 je vois pas à quelle div ouvrante elle correspond ?
Et saut de ligne ligne 31 inutile

2021-11-17 10:54 UTC, PerrinGaetan commented on src/View/Home/index.html.twig
> +<div class="title">
indenter tout ce bloc div class title avec le bloc div class trending précédent

2021-11-17 10:54 UTC, PerrinGaetan commented on src/View/ListMyGames/index.html.twig
deux saut de ligne en trop

2021-11-17 10:54 UTC, PerrinGaetan commented on src/View/ListMyGames/index.html.twig
> +
saut de ligne en trop

2021-11-17 11:08 UTC, bastienwcs approved these changes

2021-11-17 11:35 UTC, PerrinGaetan approved these changes

2021-11-17 11:42 UTC, merged