Game category
WildCodeSchool/tlse-php-202109-p2-rgb pull request #5
Opened 2021-10-31 18:20 UTC by benjamin31200

2021-10-31 18:56 UTC, PerrinGaetan requested changes

2021-10-31 18:56 UTC, PerrinGaetan commented on src/View/gameCategory/index.html.twig
> +            <button class="buttonGameCategory" type="submit">Ajouter à ma liste</button>
balise button au meme niveau d'indentation que la balise paragraphe

2021-10-31 18:56 UTC, PerrinGaetan commented on src/View/gameCategory/index.html.twig
> +
pas de saut de ligne entre la div et l'input.
Manque une balise form

2021-10-31 18:56 UTC, PerrinGaetan commented on src/View/gameCategory/index.html.twig
> +    <div class="header"> </div>
la div header doit être en dehors de ton block content

2021-11-02 09:48 UTC, PerrinGaetan reviewed
Hi Bastien,

I reviewed it and seems all is ok.
Could you tell me if i forgot somethings ?

thanks

Gaetan

2021-11-02 10:07 UTC, bastienwcs commented
Fermé, en attente de modifications du côté de Benjamin

2021-11-02 10:07 UTC, closed without merging