Navbar
WildCodeSchool/tlse-php-202109-p2-rgb pull request #8
Opened 2021-11-02 15:45 UTC by PerrinGaetan

Please merge me

2021-11-02 19:03 UTC, benjamin31200 reviewed
Rien à dire c'est le code de Monsieur propre 👍

2021-11-02 19:43 UTC, bastienwcs requested changes

2021-11-02 19:43 UTC, bastienwcs commented on public/assets/css/style.css
> +.nav{
espace avant les accolades

2021-11-02 19:43 UTC, bastienwcs commented on public/assets/javascript/scriptBurger.js
> +const burgerMenu = document.querySelector(".nav__menu__burgerButton__img");
il vaudrait mieux utiliser le menu burger fourni par Bootstrap

2021-11-03 09:16 UTC, benjamin31200 reviewed
l'espace après l'accolade dans le css à bien été rajouté, je n'ai pas repérer d'erreurs d'indentations dans le reste des fichiers.

2021-11-03 09:16 UTC, bastienwcs approved these changes

2021-11-03 09:44 UTC, merged